-- STUB
--
-- Function(s) that can return state of the object at give timestamp.
-- Preferred method - walk down from the current state of an object and apply changes stored in the audit
-- until we reach required distance back in time.
